config/routes.rb
Rails.application.routes.draw do
  root to: 'devices#index'

  resources :devices

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'search/:mac', to: 'devices#search'
      post 'alert', to: 'devices#alert'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/device.rb
# frozen_string_literal: true

class Device < ApplicationRecord
  validates :name, :mac, :cel, presence: true
  after_create :create_dashboard
  # after_update :update_dashboard

  def send_alert
    Twilio::REST::Client.new.messages.create({
      from: TWILIO['twilio_phone_number'],
      to: cel,
      body: "ALERTA #{name.upcase}: Alguém no carro!"
    })
  end

  def create_dashboard
    Grafana.create(mac)
  end
end

app/models/grafana.rb
class Grafana
  def self.create(mac)
    model = File.read(Rails.root.join('grafana/model.json'))
    model = model.gsub('xxxxxxxxxxxx', mac)
    path = File.join(Rails.root, 'grafana', 'dashboards')
    File.open(File.join(path, "#{mac}.json"), 'wb') do |f|
      f.write(model)
    end
  end

  def self.update(old_mac, new_mac)
    path = File.join(Rails.root, 'grafana', 'dashboards', "#{old_mac}.json")
    file = File.read(path)
    file = file.gsub(old_mac, new_mac)
    File.open(File.join(path), 'r+') do |f|
      f.write(file)
    end
    new_path = File.join(Rails.root, 'grafana', 'dashboards')
    system("mv #{path} #{new_path}/#{new_mac}.json")
  end
end

app/controllers/api/v1/devices_controller.rb
# frozen_string_literal: true

class Api::V1::DevicesController < ActionController::API
  before_action :find_device, only: [:search, :alert]

  def search
    if @device.blank?
      render json: 'not_found', status: :not_found
    else
      render json: { name: @device.name, cel: @device.cel }, status: :ok
    end
  end

  def alert
    if @device.blank?
      return render json: 'not_found', status: :not_found
    end
    if @device.send_alert
      render json: {}, status: :ok
    else
      render json: {}, status: :service_unavailable
    end
  end

  private

  def find_device
    @device = Device.find_by(mac: params[:mac])
    @device ||= Device.find_by(mac: params['message'])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/devices_controller.rb
# frozen_string_literal: true

class DevicesController < ApplicationController
  before_action :find_device, only: %i[show destroy edit update]

  def index
    @devices = Device.all
  end

  def show; end

  def new
    @device = Device.new
  end

  def create
    @device = Device.new(device_params)
    if @device.save
      flash[:notice] = 'Device criado com sucesso!'
      redirect_to @device
    else
      flash[:error] = 'Confira os dados e tente novamente.'
      redirect_to new_device_path
    end
  end

  def destroy
    file = Rails.root.join('grafana', 'dashboards', "#{@device.mac}.json")
    if @device.destroy
      if system("rm #{file}")
        flash[:notice] = 'Device apagado com sucesso!'
      else
        flash[:error] = 'Erro ao apagar dashboard.'
      end
    else
      flash[:error] = 'Erro ao apagar device, tente novamente.'
    end
    redirect_to root_path
  end

  def edit; end

  def update
    if update_dashboard && @device.update(device_params)
      redirect_to @device
    else
      render 'edit'
    end
  end

  private

  def find_device
    @device = Device.find(params[:id])
  end

  def device_params
    params.require(:device).permit(:name, :mac, :cel)
  end

  def update_dashboard
    Grafana.update(@device.mac, device_params[:mac])
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/devices/_form.html.erb
<%= form_with model: @device, local: true do |f|%>
  <div class="ml-5 mr-5">
    <div class="form-group">
      <%= f.label :name, 'Nome' %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :mac, 'Endereço MAC' %>
      <%= f.text_field :mac, class: 'form-control' %>
    </div>
    <div class="form-group">
      <%= f.label :cel, 'Celular' %>
      <%= f.text_field :cel, class: 'form-control' %>
    </div>
  </div>
  <%= f.submit 'Salvar', class: 'ml-5 btn btn-success' %>
<% end %>

app/views/devices/edit.html.erb
<%= render 'form' %>

<%= link_to 'Voltar', root_path, class: 'ml-5 mt-3 btn btn-secondary' %>

app/views/devices/index.html.erb
<h2>Devices</h2>

<br><hr><br>

<div class="ml-5">
  <table border="1">
    <thead>
      <tr>
        <th>Nome</th>
        <th>MAC</th>
        <th>Celular</th>
        <th>Ver mais</th>
      </tr>
    </thead>
    <tbody>
      <% @devices.each do |device| %>
        <tr>
          <td><%= device.name %></td>
          <td><%= device.mac %></td>
          <td><%= device.cel %></td>
          <td><%= link_to raw('&#128065;'), device_path(device.id), id: device.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/devices/new.html.erb
<%= render 'form' %>
<br>
<%= link_to 'Voltar', root_path, class: 'ml-5 btn btn-secondary' %>

app/views/devices/show.html.erb
<div class="ml-5">
  <h1>Device</h1>

  <h3>Nome</h3>
  <p><%= @device.name %></p>

  <h3>Endereço MAC</h3>
  <p><%= @device.mac %></p>

  <h3>Celular</h3>
  <p><%= @device.cel %></p>

  <hr>
  <%= link_to 'Editar', edit_device_path(@device.id), class: 'btn btn-info' %>
  <br>
  <%= link_to 'Apagar', device_path, method: :delete, data: { confirm: "Tem certeza?" }, class: 'btn btn-danger mt-2' %>
  <br>
  <%= link_to 'Voltar', root_path, class: 'btn btn-secondary mt-2' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IOT Panel</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <%= link_to 'IOT Panel', root_path, class: 'navbar-brand' %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item">
            <%= link_to 'Cadastro', new_device_path, class: 'nav-link' %>
          </li>
        </ul>
      </div>
    </nav>

    <% if flash[:notice] %>
      <div class="notice"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="error"><%= flash[:error] %></div>
    <% end %>

    <%= yield %>

  </body>
</html>